const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');

const directory=path.join(__dirname,'../site/assistir/hermes-em-operacao/t1e2');
const sandbox={module:{exports:{}},TextEncoder,URL};
vm.runInNewContext(fs.readFileSync(path.join(directory,'base-editorial-data.js'),'utf8'),sandbox);
vm.runInNewContext(fs.readFileSync(path.join(directory,'base-editorial-contract.js'),'utf8'),sandbox);
vm.runInNewContext(fs.readFileSync(path.join(directory,'base-editorial-ecf-scores.js'),'utf8'),sandbox);
sandbox.ECFBaseScores=sandbox.module.exports;
vm.runInNewContext(fs.readFileSync(path.join(directory,'base-editorial-bundle.js'),'utf8'),sandbox);
const stages=sandbox.ECFBaseStages,contract=sandbox.ECFBaseContract;
assert.deepEqual([...stages].map(stage=>stage.id),['negocio','pesquisa','publico','posicionamento','voz','materia-prima']);
const project={id:'local-test',business_name:'Marca de teste',records:{}};
for(const [index,stage] of stages.entries()){
  const output=contract.example(index,project);
  assert.equal(output.stage,stage.id);
  assert.doesNotThrow(()=>contract.parse(JSON.stringify(output),{id:project.id,business_name:project.business_name,stage:stage.id}));
  const prompt=contract.buildPrompt(index,project,'Ponto de partida','Contexto',stages);
  assert.match(prompt,new RegExp('ETAPA '+(index+1)+' DE 6'));
  assert.match(prompt,new RegExp('único arquivo final entregue ao usuário para upload é '+stage.id+'\\.json','i'));
  assert.match(prompt,/GitHub/);
  const invalid={...output,documents:[{...output.documents[0],path:'rascunhos/fora-do-contrato.md'}]};
  assert.throws(()=>contract.parse(JSON.stringify(invalid),{id:project.id,business_name:project.business_name,stage:stage.id}));
  const repair=contract.buildRepairPrompt(index,project,JSON.stringify(invalid),'Caminho não permitido.',stage.id+'.json');
  assert.match(repair,new RegExp('Nome obrigatório do arquivo final: '+stage.id+'\\.json'));
}
const savedProject={id:project.id,business_name:project.business_name,records:{},future_internal_note:'não exportar'};
for(const [index,stage] of stages.entries())savedProject.records[stage.id]={output:contract.example(index,project),saved_at:'2026-09-14T12:00:00.000Z'};
savedProject.diagnosis={version:1,method:'ecf-zernio-v4',axes:{creator:{score:50,measured:3,total:3,partial:false},expert:{score:50,measured:3,total:3,partial:false},founder:{score:50,measured:3,total:3,partial:false}}};
const otherProject={...savedProject,id:'outra-base',business_name:'Outra marca'};
const storage={getItem:key=>key===sandbox.ECFBaseBundle.STORAGE_KEY?JSON.stringify({version:2,active_id:savedProject.id,projects:{[savedProject.id]:savedProject,[otherProject.id]:otherProject}}):null};
const bundle=sandbox.ECFBaseBundle.activeBundle(storage,'2026-09-14T13:00:00.000Z');
assert.equal(bundle.filename,'minha-base-ecf.json');
const parsedBundle=JSON.parse(bundle.content);
assert.equal(parsedBundle.format,'agentflix-base-bundle-1');
assert.equal(parsedBundle.exported_at,'2026-09-14T13:00:00.000Z');
assert.deepEqual(Object.keys(parsedBundle.records),[...stages].map(stage=>stage.id));
assert.equal(parsedBundle.business_name,'Marca de teste');
assert.equal(parsedBundle.future_internal_note,undefined);
assert.equal(parsedBundle.projects,undefined);
let clicked=false,released=false;
sandbox.Blob=class {constructor(parts,options){this.parts=parts;this.options=options;}};
sandbox.setTimeout=callback=>callback();
const downloadAnchor={click:()=>{clicked=true;}};
const testDocument={createElement:name=>{assert.equal(name,'a');return downloadAnchor;}};
const testUrl={createObjectURL:blob=>{assert.equal(blob.parts[0],bundle.content);assert.equal(blob.options.type,'application/json');return 'blob:bundle';},revokeObjectURL:url=>{assert.equal(url,'blob:bundle');released=true;}};
assert.equal(sandbox.ECFBaseBundle.download(bundle,testDocument,testUrl),true);
assert.equal(downloadAnchor.download,'minha-base-ecf.json');
assert.equal(clicked,true);
assert.equal(released,true);
const incomplete={...savedProject,records:{...savedProject.records}};
delete incomplete.records.voz;
assert.equal(sandbox.ECFBaseBundle.activeBundle({getItem:()=>JSON.stringify({version:2,active_id:incomplete.id,projects:{[incomplete.id]:incomplete}})}),null);
const mismatched={...savedProject,id:'outro-id'};
assert.equal(sandbox.ECFBaseBundle.activeBundle({getItem:()=>JSON.stringify({version:2,active_id:savedProject.id,projects:{[savedProject.id]:mismatched}})}),null);
const malformed={...savedProject,records:{...savedProject.records,negocio:{...savedProject.records.negocio,output:{...savedProject.records.negocio.output,stage:'publico'}}}};
assert.equal(sandbox.ECFBaseBundle.activeBundle({getItem:()=>JSON.stringify({version:2,active_id:malformed.id,projects:{[malformed.id]:malformed}})}),null);
assert.equal(sandbox.ECFBaseBundle.activeBundle({getItem:()=>'{inválido'}),null);
assert.equal(sandbox.ECFBaseBundle.activeBundle({getItem:()=>JSON.stringify({version:2,active_id:'ausente',projects:{}})}),null);
console.log('PASS base editorial: seis etapas, contrato JSON, correção, exportação e skills no GitHub');
