const {chromium}=require(process.env.PLAYWRIGHT_CORE || 'playwright-core');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const base=process.env.QA_BASE||'http://127.0.0.1:8843';
const out=process.env.QA_OUT || '/tmp/agentflix-serie-materiais';
fs.mkdirSync(out,{recursive:true});
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.CHROME_FULL || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
 const errors=[]; const result=[];
 for(const width of [1440,768,390]) {
  const page=await browser.newPage({viewport:{width,height:1000},deviceScaleFactor:1});
  page.on('pageerror',e=>errors.push(e.message));
  page.on('response',r=>{if(r.url().startsWith(base)&&r.status()>=400)errors.push(`${r.status()} ${r.url()}`)});
  await page.goto(`${base}/assistir/?s=hermes-em-operacao`);
  await page.locator('#tp-materials a').waitFor({state:'attached'});
  if(await page.getByRole('button',{name:'Agora não',exact:true}).isVisible()) await page.getByRole('button',{name:'Agora não',exact:true}).click(); await page.locator('#tp-name').evaluate(el=>el.blur()); await page.evaluate(()=>document.fonts.ready); await page.locator('#tp-cover img').evaluate(img=>img.decode());
  assert.equal(await page.locator('#tp-activity').count(),0);
  assert.equal(await page.locator('.tp-actions .primary:visible').count(),1);
  assert.equal(await page.locator('.title-back svg').count(),1);
  assert.equal(await page.locator('#tp-side').textContent().then(s=>s.includes('Prática, Interativa, Didática')),true);
  const arrow=await page.locator('.title-back svg').evaluate(el=>({w:el.getBoundingClientRect().width,stroke:getComputedStyle(el).strokeWidth}));
  assert.deepEqual(arrow,{w:20,stroke:'2.5px'});
  const epCount=await page.locator('#eps .ep').count(); assert.equal(epCount,1);
  await page.screenshot({path:`${out}/after-${width}.png`,fullPage:true});
  await page.getByRole('tab',{name:'Episódios',exact:true}).focus();
  await page.keyboard.press('ArrowRight');
  assert.equal(await page.getByRole('tab',{name:'Sobre',exact:true}).getAttribute('aria-selected'),'true');
  assert.equal(await page.locator('#tab-eps').isVisible(),false);
  await page.keyboard.press('End');
  assert.equal(await page.getByRole('tab',{name:'Materiais',exact:true}).getAttribute('aria-selected'),'true');
  assert.equal(await page.locator('.tp-tab:visible').count(),1);
  assert.equal(await page.locator('#tab-sobre').isVisible(),false);
  const link=page.locator('#tp-materials a');
  assert.equal(await link.getAttribute('href'),'/assistir/hermes-em-operacao/t1e2/');
  await page.screenshot({path:`${out}/materials-${width}.png`,fullPage:true});
  await page.locator('.tp-cast summary').click();
  assert.equal(await page.locator('.tp-cast li:visible').count(),17);
  await page.screenshot({path:`${out}/cast-${width}.png`,fullPage:true});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await link.click();
  await page.waitForURL('**/hermes-em-operacao/t1e2/');
  await page.goBack();
  await page.locator('#tp-name').waitFor();
  await page.locator('.title-back').click();
  await page.waitForURL('**/assistir/');
  assert.equal(await page.locator('#title-page').isVisible(),false);
  result.push({width,arrow,materials:true,keyboard:true,cast:17,overflow:false}); await page.close();
 }
 const page=await browser.newPage(); page.on('pageerror',e=>errors.push(e.message));
 // A series with no material must not inherit the previous panel's content.
 await page.goto(`${base}/assistir/?s=hermes-agent`);
 await page.getByRole('tab',{name:'Materiais',exact:true}).click();
 await page.locator('#tp-materials .materials-empty').waitFor();
 assert.equal(await page.locator('#tp-materials a').count(),0);
 await page.getByRole('tab',{name:'Episódios',exact:true}).click();
 assert.ok(await page.locator('#eps .ep').count()>0);
 await browser.close(); assert.deepEqual(errors,[]);
 fs.writeFileSync(`${out}/${base.includes('localhost')||base.includes('127.0.0.1')?'local':'production'}-result.json`,JSON.stringify({base,result,errors},null,2));
 console.log(JSON.stringify({result,errors}));
})().catch(e=>{console.error(e);process.exit(1)});
